TEST_REPO = 'test_repo'
TEST_DESC_STAGE1_FOLDER = 'TestAnalyzer/test_desc/model_name/test_desc_stage1'
TEST_DESC_STAGE1_FOLDER_WO_VISION = 'TestAnalyzer/test_desc/model_name/test_desc_stage1_wo_vision'
TEST_DESC_GROUPED_FOLDER = 'TestAnalyzer/test_desc/model_name/test_desc_grouped'
TEST_DESC_GROUPED_FOLDER_WO_VISION = 'TestAnalyzer/test_desc/model_name/test_desc_grouped_wo_vision'
TEST_DESC_KEY_FOLDER = 'TestAnalyzer/test_desc/model_name/test_desc_key'
TEST_DESC_KEY_FOLDER_WO_VISION = 'TestAnalyzer/test_desc/model_name/test_desc_key_wo_vision'
SRC_SCREENSHOT_FOLDER = 'TestAnalyzer/src_screens_annoted'
TEST_DESC_STAGE1_IMAGE_FOLDER = 'TestAnalyzer/test_desc/test_desc_stage1_images'
TEST_DESC_KEY_IMAGE_FOLDER = 'TestAnalyzer/test_desc/model_name/test_desc_key_images'
CONFIG_FILE = 'config.csv'
CATEGORY_MAP = {"a1": "Browser", "a2": "ToDo List", "a4": "Mail Client", "a5": "Tip Calculator"}
SEMANTIC_ATTRS = ['resource-id', 'text', 'content-desc', 'class', 'event_type', 'action', 'children']
PROGRAM_ATTRS = ['class', 'package', 'activity', 'resource-id', 'text', 'content-desc', 'event_type', 'action', 'clickable', 'checkable', 'checked', 'focused', 'enabled', 'bounds']
RESULT_SAVE_FOLDER = "test_repo_migdroid"
RESULT_SAVE_FOLDER_TEMP = "test_repo_migdroid_iteration"
RESULT_SAVE_FOLDER_WO_FEEDBACK = "test_repo_migdroid_wo_feedback"
RESULT_SAVE_FOLDER_WO_VISION = "test_repo_migdroid_wo_vision"
RESULT_SAVE_FOLDER_WO_TA = "test_repo_migdroid_wo_ta"
RESULT_SAVE_FOLDER_VANILLA = "test_repo_gpt_vanilla"